server:
  port: 8082

spring:
  application:
    name: content-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.CorsAutoConfiguration
  cloud:
    consul:
      host: ${CONSUL_HOST:audit-consul}
      port: 8500
      discovery:
        register: true
        enabled: true
        service-name: content-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        instance-id: ${spring.application.name}:${server.port}
        deregister: true
        register-health-check: true
        health-check-critical-timeout: 30s
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:audit-postgres}:5432/content_audit?useSSL=false&serverTimezone=America/Los_Angeles
    username: admin
    password: admin1234
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${REDIS_HOST:audit-redis}
    port: 6379
    database: 0

# AI Service configuration
ai-service:
  base-url: http://ai-service:8083
  connect-timeout: 30000    # Connection timeout: 30 seconds
  read-timeout: 120000      # Read timeout: 120 seconds (2 minutes), supports AI batch processing

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.audit.content: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.web: DEBUG

# Add startup delay
spring.lifecycle.timeout-per-shutdown-phase: 30s

# Add delayed startup
spring.main.lazy-initialization: true

feign:
  client:
    config:
      default:
        connect-timeout: 30000    # Connection timeout: 30 seconds
        read-timeout: 120000      # Read timeout: 120 seconds (2 minutes), supports AI batch processing 