apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: content-audit
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: content-audit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 