server:
  port: 8085

spring:
  application:
    name: template-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.CorsAutoConfiguration
  cloud:
    consul:
      host: ${CONSUL_HOST:audit-consul}
      port: 8500
      discovery:
        register: true
        enabled: true
        service-name: template-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:audit-postgres}:5432/content_audit?useSSL=false&serverTimezone=America/Los_Angeles
    username: admin
    password: admin1234
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

logging:
  level:
    root: INFO
    com.audit.template: DEBUG 